services:
  backend:
    build: ./backend
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/your/config:/config:ro
      - /path/to/your/data:/data:rw
    expose:
      - "8000"

  frontend:
    build: ./frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "ports_to_expose:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro